### PR TITLE
V2 PR

### PR DESCRIPTION
**Pull request by lrvick**
This is going to be a long PR... but figured we can keep the discussion here

### CODE REVIEW

**Comment by KellerFuchs** [comment]
@lrvick It would be good if the README.md documented what is (or will be when this is merged), not what you think might perhaps be good (or not) in some distant future (re. `#!invites` in particular).
I really don't think this is the thread where we want to have the UX & abuse handling discussion this entails.

**Comment by lrvick** [comment]
This could be produced in a few days, if we agree this is a reasonable end-game. We are solving for the ssh-server signup system now, and this could all be part of the same thing.

**Comment by lrvick** [comment]
I.E. I would rather do this right the first time, and prepare for more exposure in semi-near future and set up our goals so we can get more people working in parallel depending on what they are most interested in.

**Comment by lrvick** [comment]
If we are saying #!invites is not sane for this iteration though, we could make that a v3 thing and the scope of v2 in this repo would be limited to hosting http on ports 80/443 and aagats ssh signup daemon on port 22.

**Comment by lrvick** [comment]
Yeah writing that out, I see #!invites is for sure a longer discussion. Lets focus on just ssh for a phase one. we could inject the irc bot stuff later if we decide to go that way.

**Comment by KellerFuchs** [comment]
:-)

**Comment by lrvick** [comment]
Right now there is no logic at all. Ha.  

I am thinking step 1 we go nginx to host the static page. It works, they do https right... and python/node.. don't. Logic can be separate processes behind nginxes termination.

**Comment by lrvick** [comment]
done

**Comment by lrvick** [comment]
@KellerFuchs This should be more acceptable now ;)

Going to move my other work to the new.hashbang.sh where it belongs.

**Comment by KellerFuchs** [comment]
Several things used to generate the static contents are gone:
- the source `known_hosts` file;
- the `Makefile` that was used for signing it;
- the test that was here to check that the signed file is up-to-date.

:-1:

**Comment by KellerFuchs** [comment]
OK, this seems to be dead in the water.

**Pull request closed without merging**
