### PR TITLE
known_hosts key automatic insertion

### PR DESCRIPTION
**Pull request by AlissaSquared**
Attempt at Fix - Issue 29

### CODE REVIEW

**Comment by lrvick** [comment]
+1 but I want someone elses eyes on this before we merge it.

**Comment by lrvick** [comment]
+1 from me

Want one more +1 to merge

**Comment by necrophcodr** [comment]
I'll run a test in a few moments and make sure it works, but so far so good.

**Comment by necrophcodr** [comment]
Other than that, +1 from me. One more commit should fix this.

**Comment by lrvick** [comment]
Our key is on every public keyserver, so people having whatever server is closest to them is probably still fine.

**Pull request merged**
