### PR TITLE
Fix shell sillyness

### PR DESCRIPTION
**Pull request by KellerFuchs**
This fixes a couple of bugs:
- `! $?` doesn't do what was meant in the script;
- `${privat_keyfile}` is not Russian for `${private_keyfile}`.

Aside from that, there is also a bunch of cleanups.

### CODE REVIEW

**Comment by ChickenNuggers** [comment]
```
# Check the OpenPGP signatures
rm -f -- index.html.data known_hosts
gpg --quiet -k 0xD2C4C74D8FAA96F5 ||
    gpg --recv-keys --keyserver keys.gnupg.net 0xD2C4C74D8FAA96F5
gpg: new configuration file `/home/travis/.gnupg/gpg.conf' created
gpg: WARNING: options in `/home/travis/.gnupg/gpg.conf' are not yet active during this run
gpg: error reading key: public key not found
gpg: requesting key 8FAA96F5 from hkp server keys.gnupg.net
gpg: key 8FAA96F5: public key "Hashbang Team <team@hashbang.sh>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
gpg -d -o index.html.data static/index.html
gpg: Signature made Sun 14 Feb 2016 04:17:12 PM UTC using RSA key ID 8FAA96F5
gpg: Good signature from "Hashbang Team <team@hashbang.sh>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 4562 BC56 6932 CF1C 16F2  D7CC D2C4 C74D 8FAA 96F5
diff -q index.html.data static/index.html.plain
Files index.html.data and static/index.html.plain differ
```

Most importantly, don't we -remove- `index.html.data` at the top of this section? Also, `&&` and `||` are required because `-o` and `-a` aren't as commonly supported.

**Comment by KellerFuchs** [comment]
@ChickenNuggers `-a` is [POSIX `test(1)`](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/test.html).
I don't think we should even try to support non-POSIX platforms.

**Comment by daurnimator** [comment]
> @ChickenNuggers -a is POSIX test(1).
> I don't think we should even try to support non-POSIX platforms.

Notice that in your link both -a and -o are marked OB XSI.

**Comment by KellerFuchs** [comment]
@daurnimator Good point.  Let me drop that commit, then.

**Comment by daurnimator** [comment]
> `"x$foo" = "x"` is cargo-cult

I remember we actually had to add this due to a bug report from a user.

**Comment by ChickenNuggers** [comment]
Feel free to merge and deploy. @daurnimator shellcheck isn't complaining about it, so I don't think it's necessary. The linked manual page did have -n and -z included.

**Comment by KellerFuchs** [comment]
@daurnimator Yes, I saw it: `[ -n $foo ]` can break if `$foo` is non-existent (because the whole thing gets expanded to `[ -n ]`, which is invalid...)
The right fix is to use `[ -n "$foo" ]`, which expands to `[ -n '' ]` when `$foo` does not exist.

**Pull request merged**
