### PR TITLE
Point comment at the correct line in `utils.py`

### PR DESCRIPTION
**Pull request by daveloyall**
I pointed at a specific point in time rather than the master branch, which will change.

### CODE REVIEW

**Review by KellerFuchs — CHANGES_REQUESTED** [review]
Pointing at a specific line in a specific commit and at the same time going “by the way, check the right commit” isn't super-helpful.

Perhaps something like:
> Keep in sync with the description and the server-side regexp in `validate_username`:
>  https://github.com/hashbang/provisor/blob/master/provisor/utils.py

**Comment by RyanSquared** [comment]
I agree with @KellerFuchs's review. It should be pointed to the relevant function rather than to a line which may or may not be outdated.

**Comment by daveloyall** [comment]
Ok, I've altered the language.  ...I'm afraid that the work we're putting into this costs more than the value created by the change...  Anyway, I hope someone will find it useful.

**Review by KellerFuchs — APPROVED** [review]

**Review by KellerFuchs — CHANGES_REQUESTED** [review]
@daveloyall You actially made changes in `static/` directly, rather than in the documents in `src/`.
Fixing in a second.

**Review by KellerFuchs — APPROVED** [review]

**Comment by KellerFuchs** [comment]
OK, I just force-pushed a fixed version of that patch ( @daveloyall's earlier diff, but applied to `src/hashbang.sh` ), and regenerated the signatures.

@hashbang/administrators Could someone do the signed merge and deploy?

**Comment by daveloyall** [comment]
KellerFuchs, oh, that's ... ok.  Got it.  Sorry.  Thanks!

**Comment by KellerFuchs** [comment]
@daveloyall Sorry this got stuck for 5.5 years  :grimacing: 

My life sort of flew apart right around that ted, ime, so I hadn't been involved in #! for about 5 years, and apparently none of the other admins did the final review.

I updated this to deal with merge conflicts (again), and also to point your comment at the right place: in the meantime, the Postgre-based userdb I designed was deployed, so provisor is no more, etc.

**Comment by KellerFuchs** [comment]
@RyanSquared May I trouble you again for a build & push of the container's image?  :pleading_face:

**Pull request merged**
