### PR TITLE
Update ny1's SSH host key

### PR DESCRIPTION
**Pull request by KellerFuchs**

### CODE REVIEW

**Comment by KellerFuchs** [comment]
@lrvick I mock you for not reviewing this PR.

**Comment by KellerFuchs** [comment]
@hashbang/administrators Since @lrvick finds it more useful to mock me than review patches, could one of you do it?

**Comment by daurnimator** [comment]
I can confirm the host key @KellerFuchs added matches. Approved.

**Comment by KellerFuchs** [comment]
Yay, thanks @daurnimator.

**Comment by KellerFuchs** [comment]
Deployed

**Pull request merged**
