### PR TITLE
PR for printing out errors

### PR DESCRIPTION
**Pull request by AlissaSquared**
Print out what the error was. Could be useful if it's just the account name is taken or something.

### CODE REVIEW

**Comment by necrophcodr** [comment]
It does unfortunately not work. It displays the account as created, when the response it has received is in fact HTTP/1.1 400.

**Comment by AlissaSquared** [comment]
You sure? I get error 22 if I try to use curl.

**Comment by necrophcodr** [comment]
So do I, but the script fails when using dash regardless.

**Comment by AlissaSquared** [comment]
Another point - using -f removes the output of curl. We can just make curl not keep the output and if there IS an error, the user can use the returned message.

**Comment by necrophcodr** [comment]
Make it happens, sounds good :+1:

**Comment by necrophcodr** [comment]
Doesn't fix the issue though, it still reports back that the account has been created, unfortunately. But at least it prints the error now.

**Comment by AlissaSquared** [comment]
Using `curl -f` silently errors, but using `curl` without `-f` means that we get the error message. Which is more vital? We can probably parse the error message if we really want to. There's also `curl --dump-headers` I believe.

**Comment by necrophcodr** [comment]
I'd say the latter is more vital. We want the error message, but maybe we want to decide when to show it. I don't think not using `$output` is a good idea. By all means, use that.

However, we'd also need a proper way to check if the user was created or not.

**Pull request merged**
