### PR TITLE
src/{hashbang.html,local.css}: Fix alignment of static page content

### PR DESCRIPTION
**Pull request by RyanSquared**
Currently, the website uses a static width and absolute position hackery. This instead uses flexbox and should perfectly align text on the page without cutting it off.

Pinging @lrvick to review.

### CODE REVIEW

**Comment by daurnimator** [comment]
I was worried about browser compat but seems fine: http://caniuse.com/#search=flex

**Comment by RyanSquared** [comment]
Right, browser compat was I think why we didn't do it forever ago, and I don't think there should be any issues with it now.

**Comment by KellerFuchs** [comment]
_grumbles._

**Comment by KellerFuchs** [comment]
@DeviaVir @lrvick Please review.

**Comment by RyanSquared** [comment]
Sorry, I was gonna do it as soon as I got home from work - which for me is right now. :(

**Comment by KellerFuchs** [comment]
Deployed.

@RyanSquared Can you confirm this works as intended?

**Comment by RyanSquared** [comment]
@KellerFuchs yes it works, the text (for the most part) is centered with a few issues due to my own browser being weird, but overall it is centered on the page, and the text is not cut off.

**Pull request merged**
